version: '3.8'
services:
  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    volumes:
      - ./:/usr/app
    working_dir: '/usr/app/packages/front'
    command: 'npm run dev'
    ports:
      - '3000:3000'
    tty: true
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    volumes:
      - ./:/usr/app
    working_dir: '/usr/app/packages/server'
    command: 'sh ../../docker/start.sh'
    ports:
      - '5555:5555'
      - '8080:8080'
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/var/lib/mysql
