version: '3.8'
services:
  server:
    build: .
    volumes:
      - ./:/usr/app
    command: 'npm run start:dev'
    ports:
      - '3000:3000'
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./prisma/mysql:/var/lib/mysql
